### ISSUE TITLE
Neon.Deployment: GitHubPackageApi.ListAsync() has stopped working

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonSDK#54]
**neon-image prepare node** has just started failing with:

```
*** ERROR: [Neon.Net.HttpException]: HTTP ERROR:  status=[502] method=GET uri=https://api.github.com/orgs/neonkube-dev/packages/container/prometheus-operator-prometheus-operator/versions?per_page=100 reason=[Bad Gateway]
   at Neon.Net.JsonResponse.EnsureSuccess() in C:\src\neonSDK\Lib\Neon.Common\Net\JsonResponse.cs:line 160
   at Neon.Net.JsonClient.<>c__DisplayClass40_0.<<GetAsync>b__0>d.MoveNext() in C:\src\neonSDK\Lib\Neon.Common\Net\JsonClient.Get.cs:line 82
--- End of stack trace from previous location ---
   at Neon.Retry.ExponentialRetryPolicy.InvokeAsync[TResult](Func`1 action) in C:\src\neonSDK\Lib\Neon.Common\Retry\ExponentialRetryPolicy.cs:line 300
   at Neon.Retry.ExponentialRetryPolicy.InvokeAsync[TResult](Func`1 action) in C:\src\neonSDK\Lib\Neon.Common\Retry\ExponentialRetryPolicy.cs:line 308
   at Neon.Net.JsonClient.GetAsync(String uri, ArgDictionary args, ArgDictionary headers, CancellationToken cancellationToken) in C:\src\neonSDK\Lib\Neon.Common\Net\JsonClient.Get.cs:line 65
   at Neon.Deployment.GitHubExtensions.GetPaginatedAsync(JsonClient client, String uri, Int32 maxItemsPerPage) in C:\src\neonSDK\Lib\Neon.Deployment\GitHub\GitHubExtensions.cs:line 99
   at Neon.Deployment.GitHubPackageApi.ListAsync(String organization, String nameOrPattern, GitHubPackageType packageType, GitHubPackageVisibility visibility, Boolean includeVersions) in C:\src\neonSDK\Lib\Neon.Deployment\GitHub\Packages\GitHubPackageApi.cs:line 132
   at NeonImage.PrepareNodeCommand.RunAsync(CommandLine commandLine) in C:\src\neonCLOUD\Tools\neon-image\Commands\Prepare\PrepareNodeCommand.cs:line 344
   at NeonImage.Program.Main(String[] args) in C:\src\neonCLOUD\Tools\neon-image\Program.cs:line 428
```

when verifying the setup container images.

**Comment by jefflill** [comment]
This is working again: must have been a transient GitHub issue.
